apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gc-signin-static-website
  title: GC Sign Static Website
  description: Landing page and central source of information for potential clients that are interested in CanadaLogin
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: group:cds-snc/digital-credentials-gc-sign-in
  system: gc-signin-solution

