apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gc-signin
  description: >-
    CanadaLogin informational page
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
